import React, { useEffect, useState, useRef } from 'react';
import { supabase } from '../supabaseClient';
import { Phone, Video, PhoneOff, MicOff, Mic, VideoOff, Volume2 } from 'lucide-react';

export default function CallScreen({ currentUser, activeCall, onCallEnd }) {
  const [callStatus, setCallStatus] = useState(activeCall.status); // 'ringing', 'connected', 'ended', 'rejected'
  const [localStream, setLocalStream] = useState(null);
  const [remoteStream, setRemoteStream] = useState(null);
  const [isMuted, setIsMuted] = useState(false);
  const [isCameraOff, setIsCameraOff] = useState(activeCall.type === 'audio');

  const peerConnectionRef = useRef(null);
  const localVideoRef = useRef(null);
  const remoteVideoRef = useRef(null);
  const isCaller = activeCall.role === 'caller';
  const callId = activeCall.id;

  const iceServers = {
    iceServers: [
      { urls: 'stun:stun.l.google.com:19302' },
      { urls: 'stun:stun1.l.google.com:19302' },
      { urls: 'stun:stun2.l.google.com:19302' },
    ],
  };

  useEffect(() => {
    // 1. Get user media (webcam/mic)
    setupLocalMedia();

    // 2. Set up Supabase Realtime subscriptions to listen to call updates and signaling
    const callSubscription = supabase
      .channel(`call_channel_${callId}`)
      .on(
        'postgres_changes',
        { event: 'UPDATE', schema: 'public', table: 'calls', filter: `id=eq.${callId}` },
        (payload) => {
          handleCallStatusUpdate(payload.new);
        }
      )
      .on(
        'postgres_changes',
        { event: 'INSERT', schema: 'public', table: 'call_signaling', filter: `call_id=eq.${callId}` },
        (payload) => {
          handleIncomingSignaling(payload.new);
        }
      )
      .subscribe();

    return () => {
      callSubscription.unsubscribe();
      cleanupCall();
    };
  }, []);

  // Update local video element when stream is ready
  useEffect(() => {
    if (localVideoRef.current && localStream) {
      localVideoRef.current.srcObject = localStream;
    }
  }, [localStream]);

  // Update remote video element when stream is ready
  useEffect(() => {
    if (remoteVideoRef.current && remoteStream) {
      remoteVideoRef.current.srcObject = remoteStream;
    }
  }, [remoteStream]);

  const setupLocalMedia = async () => {
    try {
      const constraints = {
        audio: true,
        video: activeCall.type === 'video',
      };
      const stream = await navigator.mediaDevices.getUserMedia(constraints);
      setLocalStream(stream);

      // If we are the caller, we initialize the peer connection and create the offer
      if (isCaller) {
        initiateWebRTCPeer(stream);
      }
    } catch (err) {
      console.error('Failed to get media devices:', err);
      alert('Could not access camera/microphone. Continuing audio-only if possible.');
      // Fallback to audio only
      try {
        const audioStream = await navigator.mediaDevices.getUserMedia({ audio: true });
        setLocalStream(audioStream);
        if (isCaller) {
          initiateWebRTCPeer(audioStream);
        }
      } catch (audioErr) {
        console.error('Failed fallback to audio:', audioErr);
        handleHangup();
      }
    }
  };

  const initiateWebRTCPeer = (stream) => {
    const pc = new RTCPeerConnection(iceServers);
    peerConnectionRef.current = pc;

    // Add local tracks to peer connection
    stream.getTracks().forEach((track) => {
      pc.addTrack(track, stream);
    });

    // Handle ICE candidates generated by browser
    pc.onicecandidate = (event) => {
      if (event.candidate) {
        sendSignalingPayload('candidate', event.candidate.toJSON());
      }
    };

    // Handle incoming remote track
    pc.ontrack = (event) => {
      if (event.streams && event.streams[0]) {
        setRemoteStream(event.streams[0]);
      }
    };

    // Create SDP Offer
    pc.createOffer()
      .then((offer) => pc.setLocalDescription(offer))
      .then(() => {
        sendSignalingPayload('offer', pc.localDescription);
      })
      .catch((err) => console.error('Error creating offer:', err));
  };

  const answerWebRTCPeer = async (stream, offerDescription) => {
    const pc = new RTCPeerConnection(iceServers);
    peerConnectionRef.current = pc;

    // Add local tracks
    stream.getTracks().forEach((track) => {
      pc.addTrack(track, stream);
    });

    pc.onicecandidate = (event) => {
      if (event.candidate) {
        sendSignalingPayload('candidate', event.candidate.toJSON());
      }
    };

    pc.ontrack = (event) => {
      if (event.streams && event.streams[0]) {
        setRemoteStream(event.streams[0]);
      }
    };

    try {
      // Set remote offer
      await pc.setRemoteDescription(new RTCSessionDescription(offerDescription));

      // Create answer
      const answer = await pc.createAnswer();
      await pc.setLocalDescription(answer);

      // Send answer
      sendSignalingPayload('answer', pc.localDescription);
    } catch (err) {
      console.error('Error answering call:', err);
    }
  };

  const sendSignalingPayload = async (type, payload) => {
    try {
      await supabase.from('call_signaling').insert({
        call_id: callId,
        sender_id: currentUser.id,
        type,
        payload,
      });
    } catch (err) {
      console.error('Error sending signal:', err);
    }
  };

  const handleCallStatusUpdate = (updatedCall) => {
    setCallStatus(updatedCall.status);
    if (updatedCall.status === 'connected' && !isCaller) {
      // Receiver connects: they need to start peer connection setup using their local media stream
      if (localStream) {
        // Fetch original offer to answer it
        fetchAndAnswerOffer();
      }
    } else if (updatedCall.status === 'ended' || updatedCall.status === 'rejected') {
      onCallEnd();
    }
  };

  const fetchAndAnswerOffer = async () => {
    try {
      const { data, error } = await supabase
        .from('call_signaling')
        .select('*')
        .eq('call_id', callId)
        .eq('type', 'offer')
        .limit(1);

      if (error) throw error;
      if (data && data.length > 0) {
        answerWebRTCPeer(localStream, data[0].payload);
      }
    } catch (err) {
      console.error('Error fetching offer:', err);
    }
  };

  const handleIncomingSignaling = async (signal) => {
    // Ignore signaling sent by ourselves
    if (signal.sender_id === currentUser.id) return;

    const pc = peerConnectionRef.current;
    if (!pc) return;

    try {
      if (signal.type === 'answer') {
        await pc.setRemoteDescription(new RTCSessionDescription(signal.payload));
      } else if (signal.type === 'candidate') {
        await pc.addIceCandidate(new RTCIceCandidate(signal.payload));
      }
    } catch (err) {
      console.error('Error applying remote signaling:', err);
    }
  };

  // Run answer setup if status was already 'connected' when localStream finished initializing (for receiver)
  useEffect(() => {
    if (localStream && callStatus === 'connected' && !isCaller && !peerConnectionRef.current) {
      fetchAndAnswerOffer();
    }
  }, [localStream, callStatus]);

  const handleAccept = async () => {
    try {
      await supabase
        .from('calls')
        .update({ status: 'connected' })
        .eq('id', callId);
      setCallStatus('connected');
    } catch (err) {
      console.error('Error accepting call:', err);
    }
  };

  const handleHangup = async () => {
    try {
      const statusToSet = callStatus === 'ringing' && !isCaller ? 'rejected' : 'ended';
      await supabase
        .from('calls')
        .update({ status: statusToSet })
        .eq('id', callId);
    } catch (err) {
      console.error('Error updating hangup state:', err);
    } finally {
      onCallEnd();
    }
  };

  const toggleMute = () => {
    if (localStream) {
      localStream.getAudioTracks().forEach((track) => {
        track.enabled = !track.enabled;
      });
      setIsMuted(!isMuted);
    }
  };

  const toggleCamera = () => {
    if (localStream) {
      localStream.getVideoTracks().forEach((track) => {
        track.enabled = !track.enabled;
      });
      setIsCameraOff(!isCameraOff);
    }
  };

  const cleanupCall = () => {
    if (peerConnectionRef.current) {
      peerConnectionRef.current.close();
      peerConnectionRef.current = null;
    }
    if (localStream) {
      localStream.getTracks().forEach((track) => track.stop());
      setLocalStream(null);
    }
    setRemoteStream(null);
  };

  const isVideo = activeCall.type === 'video';

  return (
    <div className="call-overlay">
      {callStatus === 'ringing' && !isCaller ? (
        // Incoming call view
        <div className="incoming-call-box glass-panel">
          <div className="caller-avatar">
            {activeCall.otherMemberName?.substring(0, 2).toUpperCase()}
          </div>
          <div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 600 }}>{activeCall.otherMemberName}</h3>
            <p style={{ color: 'var(--text-secondary)', marginTop: '4px' }}>
              Incoming {isVideo ? 'Video' : 'Audio'} Call...
            </p>
          </div>
          <div className="call-actions-row">
            <button onClick={handleHangup} className="call-btn decline" title="Decline">
              <PhoneOff size={24} />
            </button>
            <button onClick={handleAccept} className="call-btn accept" title="Accept">
              <Phone size={24} />
            </button>
          </div>
        </div>
      ) : (
        // Ringing outgoing OR Active Connected Call view
        <div className="call-card glass-panel">
          <div className={`video-grid ${isVideo && remoteStream ? 'two-streams' : ''}`}>
            {/* Remote Stream Video */}
            {isVideo ? (
              <div className="video-wrapper">
                {remoteStream ? (
                  <video
                    ref={remoteVideoRef}
                    autoPlay
                    playsInline
                    className="video-stream"
                  />
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px' }}>
                    <div className="caller-avatar" style={{ animation: 'pulse 1.5s infinite' }}>
                      {activeCall.otherMemberName?.substring(0, 2).toUpperCase()}
                    </div>
                    <span style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                      {callStatus === 'ringing' ? 'Ringing...' : 'Waiting for connection...'}
                    </span>
                  </div>
                )}
                {remoteStream && (
                  <span className="call-member-tag">{activeCall.otherMemberName}</span>
                )}
              </div>
            ) : (
              // Audio Call layout (no video stream display, just statuses)
              <div style={{ display: 'flex', flex: 1, flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '16px' }}>
                <div className="caller-avatar">
                  {activeCall.otherMemberName?.substring(0, 2).toUpperCase()}
                </div>
                <div style={{ textAlign: 'center' }}>
                  <h3>{activeCall.otherMemberName}</h3>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '6px' }}>
                    {callStatus === 'ringing' ? 'Calling...' : 'Connected (Audio)'}
                  </p>
                </div>
              </div>
            )}

            {/* Local Stream PIP (Picture in Picture) for Video Calls */}
            {isVideo && localStream && (
              <div className="local-video-pip">
                <video
                  ref={localVideoRef}
                  autoPlay
                  playsInline
                  muted
                  className="video-stream"
                  style={{ transform: 'scaleX(-1)' }} // Mirror local view
                />
              </div>
            )}
          </div>

          {/* Controls overlay */}
          <div className="call-controls-overlay">
            <button
              onClick={toggleMute}
              className={`call-btn mute ${isMuted ? 'active' : ''}`}
              title={isMuted ? 'Unmute Mic' : 'Mute Mic'}
            >
              {isMuted ? <MicOff size={20} /> : <Mic size={20} />}
            </button>

            {isVideo && (
              <button
                onClick={toggleCamera}
                className={`call-btn mute ${isCameraOff ? 'active' : ''}`}
                title={isCameraOff ? 'Turn Camera On' : 'Turn Camera Off'}
              >
                {isCameraOff ? <VideoOff size={20} /> : <Video size={20} />}
              </button>
            )}

            <button onClick={handleHangup} className="call-btn decline" title="End Call">
              <PhoneOff size={20} />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
